name: Java CI with Gradle

on:
  push:
    paths: 
      - 'src/**'
      - 'build.gradle'
      - 'gradlew'
      - 'gradlew.bat'
  pull_request:
    paths-ignore: 
      - 'src/**'
      - 'build.gradle'
      - 'gradlew'
      - 'gradlew.bat'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '22'

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle
    
    - name: Build with Gradle
      if: runner.os != 'Windows'
      run: ./gradlew build

    - name: Package as executable JAR
      if: runner.os != 'Windows'
      run: ./gradlew jar

    - name: Build with Gradle (Windows)
      if: runner.os == 'Windows'
      run: ./gradlew.bat build

    - name: Package as executable JAR (Windows)
      if: runner.os == 'Windows'
      run: ./gradlew.bat jar

    - name: Upload JAR file
      uses: actions/upload-artifact@v2
      with:
        name: war.jar
        path: build/libs/war.jar